image: Visual Studio 2017

build_script:
  - cmd: fake.cmd build -t RunCI

environment:
  nuget_api_key:
    secure: uxeBhnDDyowaBY1oDNFPo9Yz9wbJUWwAw8BgagEbHtKLQR3uxOADA7dvO+pcANt0

artifacts:
  - path: build_output\*.nupkg