version: 2
general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

jobs:
  build:
    docker:
      - image: andrewlock/dotnet-mono
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name: run-tests
          command: |
            export TERM=xterm-256color
            ./fake.sh build -t RunCI